In [2]:
import torch
# 示例 2: 从向量创建对角矩阵 (返回2D tensor)
vector = torch.tensor([0, 20, 30])
diagonal_matrix = torch.diag(vector)
print("\n原向量:\n", vector)
print("从向量创建的对角矩阵:\n", diagonal_matrix)
# 输出:
# tensor([[10,  0,  0],
#         [ 0, 20,  0],
#         [ 0,  0, 30]])


原向量:
 tensor([ 0, 20, 30])
从向量创建的对角矩阵:
 tensor([[ 0,  0,  0],
        [ 0, 20,  0],
        [ 0,  0, 30]])
